# Use an official Node.js image as the base image
FROM node:20.17.0-bullseye

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files first to leverage Docker caching
COPY package.json ./

# Install dependencies
RUN npm cache clean --force
RUN npm install
#RUN ["npm", "install", "react-icons", "--save"]

# Copy the rest of the application source code
COPY . .

# Set environment variables for development
ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=true  

# Expose port 3000 for the React development server
EXPOSE 3000

# Start the React app using the npm start command
CMD ["npm", "start"]
