# Use an official Node.js image as the base image
FROM node:20.17.0-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files first to leverage Docker caching
COPY package*.json ./

# Install dependencies
RUN npm Install

# Copy the rest of the application source code
COPY . .

RUN npm build